package com.space_153925.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Application implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Years of amortization")
	private java.lang.Integer amortization;
	@org.kie.api.definition.type.Label(value = "Applicant")
	private com.space_153925.mortgage.Applicant applicant;
	@org.kie.api.definition.type.Label(value = "Down Payment")
	private java.lang.Integer downpayment;

	public Application() {
	}

	public java.lang.Integer getAmortization() {
		return this.amortization;
	}

	public void setAmortization(java.lang.Integer amortization) {
		this.amortization = amortization;
	}

	public com.space_153925.mortgage.Applicant getApplicant() {
		return this.applicant;
	}

	public void setApplicant(com.space_153925.mortgage.Applicant applicant) {
		this.applicant = applicant;
	}

	public java.lang.Integer getDownpayment() {
		return this.downpayment;
	}

	public void setDownpayment(java.lang.Integer downpayment) {
		this.downpayment = downpayment;
	}

	public Application(java.lang.Integer amortization,
			com.space_153925.mortgage.Applicant applicant,
			java.lang.Integer downpayment) {
		this.amortization = amortization;
		this.applicant = applicant;
		this.downpayment = downpayment;
	}

}