package com.space_153925.mortgage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Property implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Address of property")
	private java.lang.String address;
	@org.kie.api.definition.type.Label("Age of property")
	private java.lang.Integer age;
	@org.kie.api.definition.type.Label("Locale")
	private java.lang.String locale;
	@org.kie.api.definition.type.Label("Sale Price")
	private java.lang.Integer salesprice;

	@org.kie.api.definition.type.Label(value = "Error details")
	private com.space_153925.mortgage.ValidationErrorDO errors;

	@org.kie.api.definition.type.Label(value = "Mortgage amount")
	private java.lang.Integer mortgageamount;

	@org.kie.api.definition.type.Label(value = "Property")
	private com.space_153925.mortgage.Property property;

	public Property() {
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.Integer getAge() {
		return this.age;
	}

	public void setAge(java.lang.Integer age) {
		this.age = age;
	}

	public java.lang.String getLocale() {
		return this.locale;
	}

	public void setLocale(java.lang.String locale) {
		this.locale = locale;
	}

	public java.lang.Integer getSalesprice() {
		return this.salesprice;
	}

	public void setSalesprice(java.lang.Integer salesprice) {
		this.salesprice = salesprice;
	}

	public com.space_153925.mortgage.ValidationErrorDO getErrors() {
		return this.errors;
	}

	public void setErrors(com.space_153925.mortgage.ValidationErrorDO errors) {
		this.errors = errors;
	}

	public java.lang.Integer getMortgageamount() {
		return this.mortgageamount;
	}

	public void setMortgageamount(java.lang.Integer mortgageamount) {
		this.mortgageamount = mortgageamount;
	}

	public com.space_153925.mortgage.Property getProperty() {
		return this.property;
	}

	public void setProperty(com.space_153925.mortgage.Property property) {
		this.property = property;
	}

	public Property(java.lang.String address, java.lang.Integer age,
			java.lang.String locale, java.lang.Integer salesprice,
			com.space_153925.mortgage.ValidationErrorDO errors,
			java.lang.Integer mortgageamount,
			com.space_153925.mortgage.Property property) {
		this.address = address;
		this.age = age;
		this.locale = locale;
		this.salesprice = salesprice;
		this.errors = errors;
		this.mortgageamount = mortgageamount;
		this.property = property;
	}

}